- name: Deploy server applications
  hosts: svr1
  roles:
    - role: authentik
      tags: authentik

    - role: caddy
      tags: caddy

    - role: cup
      tags: cup

    - role: dawarich
      tags: dawarich

    - role: dockge
      tags: dockge

    - role: homepage
      tags: homepage

    - role: immich
      tags: immich

    - role: jellyfin
      tags: jellyfin

    - role: linkwarden
      tags: linkwarden

    - role: nginx
      tags: nginx

    - role: ollama
      tags: ollama

    - role: paperless-ngx
      tags: paperless

    - role: photon
      tags: photon

    - role: pi-hole
      tags: pihole

    - role: uptime-kuma
      tags: uptime-kuma

    - role: wallabag
      tags: wallabag
