name: homepage
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:v1.9.0
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - "3000:3000"
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.246
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_ALLOWED_HOSTS: "192.168.178.117:3000,bl4ckspell.freeddns.org,homepage.bl4ckspell.freeddns.org"
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id

networks:
  default:
    driver: bridge
  svr1-network:
    external: true