name: linkwarden
services:
  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:v2.13.5
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 3010:3000
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.250
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@linkwarden-postgres:5432/postgres
      NEXT_PUBLIC_OLLAMA_ENDPOINT_URL: http://ollama.lan:11434
      OLLAMA_MODEL: mistral
    volumes:
      - ./data:/data/data
    depends_on:
      - linkwarden-postgres
      - linkwarden-meilisearch

  linkwarden-postgres:
    container_name: linkwarden-postgres
    image: postgres:16-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  linkwarden-meilisearch:
    container_name: linkwarden-meilisearch
    image: getmeili/meilisearch:v1.12.8
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data

networks:
  default:
    driver: bridge
  svr1-network:
    external: true
