- name: Install Flatpak applications from Flathub
  become: true
  community.general.flatpak:
    method: system
    remote: flathub
    state: present
    name:
      - com.github.tchx84.Flatseal
      - com.leinardi.gst
      - com.mattjakeman.ExtensionManager
      - io.github.nokse22.inspector
      - io.missioncenter.MissionCenter
      - org.gnome.Firmware
      - org.localsend.localsend_app
