---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Server:
    - Essential:
        - Anubis:
            icon: sh-anubis.png
            description: AI-powered bot protection
            ping: anubis.lan
            statusStyle: "basic"

        - Caddy:
            icon: sh-caddy.svg
            description: Reverse-Proxy
            ping: caddy.lan
            statusStyle: "basic"

        - Nginx Proxy Manager:
            icon: sh-nginx-proxy-manager.svg
            href: https://npm.bl4ckspell.freeddns.org/
            description: Reverse-Proxy
            ping: npm.lan
            statusStyle: "basic"

        - Pi-hole:
            icon: sh-pi-hole.svg
            href: https://pihole.bl4ckspell.freeddns.org/admin/
            description: DNS Server & Filter
            ping: pihole.lan
            statusStyle: "basic"

    - Management & Monitoring:
        - Dockge:
            icon: sh-dockge.svg
            href: https://dockge.bl4ckspell.freeddns.org/
            description: Docker Stacks Management
            ping: dockge.lan
            statusStyle: "basic"

        - Uptime-Kuma:
            icon: sh-uptime-kuma.svg
            href: https://kuma.bl4ckspell.freeddns.org/
            description: Status
            ping: kuma.lan
            statusStyle: "basic"

        - ddns-updater:
            icon: sh-ddns-updater.svg
            description: Dynamic DNS Updater
            ping: ddns-updater.lan
            statusStyle: "basic"

        - Dockhand:
            icon: sh-dockhand.png
            href: https://dockhand.bl4ckspell.freeddns.org/
            description: Docker Container Management
            ping: dockhand.lan
            statusStyle: "basic"

        - Cup:
            icon: sh-cup-updates.svg
            href: https://cup.bl4ckspell.freeddns.org/
            description: Docker container updates made easy.
            ping: cup.lan
            statusStyle: "basic"
            widget:
              type: customapi
              url: http://cup.lan:8000/api/v3/json
              refreshInterval: 10000
              method: GET
              mappings:
                - field: metrics.monitored_images
                  label: Monitored images
                  format: number
                - field: metrics.up_to_date
                  label: Up to date
                  format: number
                - field: metrics.updates_available
                  label: Available updates
                  format: number

    - AI & Data:
        - Ollama:
            icon: sh-ollama.svg
            description: Local AI models
            ping: ollama.lan
            statusStyle: "basic"

        - Photon:
            icon: /icons/photon.png
            description: Geocoder
            ping: photon.lan
            statusStyle: "basic"

- Services:
    - SSO:
        - Authentik:
            icon: sh-authentik.svg
            href: https://authentik.bl4ckspell.freeddns.org/
            description: Login
            ping: authentik.lan
            statusStyle: "basic"

    - Tools:
        - Dawarich:
            icon: sh-dawarich.svg
            href: https://dawarich.bl4ckspell.freeddns.org/
            description: Location History Tracker
            ping: dawarich.lan
            statusStyle: "basic"

        - Immich:
            icon: sh-immich.svg
            href: https://immich.bl4ckspell.freeddns.org/
            description: High performance self-hosted photo and video management solution.
            ping: immich.lan
            statusStyle: "basic"

        - Jellyfin:
            icon: sh-jellyfin.svg
            href: https://jellyfin.bl4ckspell.freeddns.org/
            description: The Free Software Media System
            ping: jellyfin.lan
            statusStyle: "basic"

        - Linkwarden:
            icon: sh-linkwarden.svg
            href: https://linkwarden.bl4ckspell.freeddns.org/
            description: Collect, read, annotate, and preserve your webpages.
            ping: linkwarden.lan
            statusStyle: "basic"

        - Paperless:
            icon: sh-paperless-ngx.svg
            href: https://paperless.bl4ckspell.freeddns.org/
            description: Document management
            ping: paperless.lan
            statusStyle: "basic"
