name: cup
services:
  cup:
    container_name: cup
    image: ghcr.io/sergi0g/cup:v3.5.1
    restart: unless-stopped
    command: -c /config/cup.json serve
    ports:
      # Host Port : Container Port
      - 8010:8000
    networks:
      default:
      svr1-network:
        ipv4_address: 172.21.255.242
    dns:
      - 172.21.255.254
    dns_search: # don't append any search domain
      - "."
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cup.json:/config/cup.json

networks:
  default:
    driver: bridge
  svr1-network:
    external: true
