- name: Ensure Wallabag directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /opt/stacks/wallabag
    - /opt/stacks/wallabag/images

  # fix: [ERROR] Bad magic header in tc log
- name: Ensure MariaDB data directory exists with correct ownership
  ansible.builtin.file:
    path: /opt/stacks/wallabag/data
    state: directory
    owner: "999" # mysql
    group: "999" # mysql
    mode: "0755"

- name: Load secrets for Wallabag
  ansible.builtin.include_vars:
    file: "secrets.yml"

- name: Template wallabag .env file
  ansible.builtin.template:
    src: wallabag.env.j2
    dest: /opt/stacks/wallabag/.env
    owner: root
    group: root
    mode: "0600"

- name: Copy Wallabag docker-compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/stacks/wallabag/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Start Wallabag
  community.docker.docker_compose_v2:
    project_src: /opt/stacks/wallabag
    state: present
    files:
      - docker-compose.yml
    remove_orphans: true
  register: wallabag_result

- name: Debug Docker Compose result
  ansible.builtin.debug:
    var: wallabag_result
