name: photon
services:
  photon:
    container_name: photon
    image: rtuszik/photon-docker:1.3.1
    restart: unless-stopped
    environment:
      UPDATE_STRATEGY: PARALLEL
      UPDATE_INTERVAL: 14d
      REGION: europe # Optional: specific region (continent, country, or planet)
      BASE_URL: https://download1.graphhopper.com/public/ # Official
      # BASE_URL: https://r2.koalasec.org/public # Community mirror
      DOWNLOAD_MAX_RETRIES: 5
      FORCE_UPDATE: FALSE
      LOG_LEVEL: INFO
      SKIP_MD5_CHECK: FALSE
    volumes:
      - photon_data:/photon/data
    networks:
      svr1-network:
        ipv4_address: 172.21.255.245
    dns:
      - 172.21.255.254
    dns_search:
      - "."
    ports:
      # Host Port : Container Port
      - "2322:2322"
    healthcheck:
      test: ["NONE"]

volumes:
  photon_data:

networks:
  svr1-network:
    external: true
